// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: chat/v1/chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BroadcastServiceClient is the client API for BroadcastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BroadcastServiceClient interface {
	ServerMessageStream(ctx context.Context, in *ServerMessageStreamRequest, opts ...grpc.CallOption) (BroadcastService_ServerMessageStreamClient, error)
	ClientMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error)
	GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*User, error)
}

type broadcastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastServiceClient(cc grpc.ClientConnInterface) BroadcastServiceClient {
	return &broadcastServiceClient{cc}
}

func (c *broadcastServiceClient) ServerMessageStream(ctx context.Context, in *ServerMessageStreamRequest, opts ...grpc.CallOption) (BroadcastService_ServerMessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &BroadcastService_ServiceDesc.Streams[0], "/chat.v1.BroadcastService/ServerMessageStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcastServiceServerMessageStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BroadcastService_ServerMessageStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type broadcastServiceServerMessageStreamClient struct {
	grpc.ClientStream
}

func (x *broadcastServiceServerMessageStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *broadcastServiceClient) ClientMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error) {
	out := new(Close)
	err := c.cc.Invoke(ctx, "/chat.v1.BroadcastService/ClientMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastServiceClient) GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/chat.v1.BroadcastService/GetCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BroadcastServiceServer is the server API for BroadcastService service.
// All implementations must embed UnimplementedBroadcastServiceServer
// for forward compatibility
type BroadcastServiceServer interface {
	ServerMessageStream(*ServerMessageStreamRequest, BroadcastService_ServerMessageStreamServer) error
	ClientMessage(context.Context, *Message) (*Close, error)
	GetCurrentUser(context.Context, *GetCurrentUserRequest) (*User, error)
	mustEmbedUnimplementedBroadcastServiceServer()
}

// UnimplementedBroadcastServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBroadcastServiceServer struct {
}

func (UnimplementedBroadcastServiceServer) ServerMessageStream(*ServerMessageStreamRequest, BroadcastService_ServerMessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerMessageStream not implemented")
}
func (UnimplementedBroadcastServiceServer) ClientMessage(context.Context, *Message) (*Close, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientMessage not implemented")
}
func (UnimplementedBroadcastServiceServer) GetCurrentUser(context.Context, *GetCurrentUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedBroadcastServiceServer) mustEmbedUnimplementedBroadcastServiceServer() {}

// UnsafeBroadcastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcastServiceServer will
// result in compilation errors.
type UnsafeBroadcastServiceServer interface {
	mustEmbedUnimplementedBroadcastServiceServer()
}

func RegisterBroadcastServiceServer(s grpc.ServiceRegistrar, srv BroadcastServiceServer) {
	s.RegisterService(&BroadcastService_ServiceDesc, srv)
}

func _BroadcastService_ServerMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerMessageStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcastServiceServer).ServerMessageStream(m, &broadcastServiceServerMessageStreamServer{stream})
}

type BroadcastService_ServerMessageStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type broadcastServiceServerMessageStreamServer struct {
	grpc.ServerStream
}

func (x *broadcastServiceServerMessageStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _BroadcastService_ClientMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServiceServer).ClientMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.v1.BroadcastService/ClientMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServiceServer).ClientMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _BroadcastService_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastServiceServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.v1.BroadcastService/GetCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastServiceServer).GetCurrentUser(ctx, req.(*GetCurrentUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BroadcastService_ServiceDesc is the grpc.ServiceDesc for BroadcastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BroadcastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.BroadcastService",
	HandlerType: (*BroadcastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientMessage",
			Handler:    _BroadcastService_ClientMessage_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _BroadcastService_GetCurrentUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerMessageStream",
			Handler:       _BroadcastService_ServerMessageStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat/v1/chat.proto",
}
